project_id = "omijwwvticrqbxqxqwnw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.execute-code]
verify_jwt = true

[functions.ai-assistant]
verify_jwt = true